export const ADMIN_VIEW = {
  TITLE: 'All consultations',
  READ_ONLY: 'Read-only',
  DESCRIPTION: 'A complete overview of every consultation across all students.',
  STAT_TOTAL: 'Total consultations',
  STAT_UPCOMING: 'Upcoming',
  STAT_STUDENTS: 'Students',
  RECORDS_TITLE: 'Consultation records',
  SEARCH_PLACEHOLDER: 'Search student or reason',
  CLEAR_SEARCH: 'Clear search',
  STATUS_PLACEHOLDER: 'Status',
  ALL_STATUSES: 'All statuses',
  HEAD_STUDENT: 'Student',
  HEAD_REASON: 'Reason',
  HEAD_DATE: 'Date',
  HEAD_TIME: 'Time',
  HEAD_STATUS: 'Status',
  ERROR_TITLE: "Couldn't load consultations",
  ERROR_DESCRIPTION: "The scheduling service didn't respond. Please try again.",
  RETRY: 'Retry',
  REFRESH: 'Refresh table',
  EMPTY_TITLE: 'No matching consultations',
  EMPTY_DESCRIPTION: 'Try adjusting your search or status filter.',
  PAGE: 'Page',
  PAGE_OF: 'of',
  PREVIOUS: 'Previous',
  NEXT: 'Next',
} as const;
