export const BOOKING_FORM = {
  TITLE: 'Consultation details',
  DESCRIPTION: "Tell us who you are and what you'd like to discuss.",
  SUCCESS_TITLE: 'Consultation booked',
  SUCCESS_DESCRIPTION: 'Redirecting you to your dashboard...',
  ERROR_TITLE: 'Unable to book',
  FIRST_NAME_LABEL: 'First name',
  LAST_NAME_LABEL: 'Last name',
  REASON_LABEL: 'Reason for consultation',
  REASON_PLACEHOLDER: 'e.g. Discuss course selection and degree requirements for next semester.',
  DATE_LABEL: 'Date',
  DATE_PLACEHOLDER: 'Pick a date',
  TIME_LABEL: 'Time',
  SUBMIT: 'Book consultation',
  SUBMITTING: 'Booking...',
  SUBMITTED: 'Booked',
  CANCEL: 'Cancel',
  GENERIC_ERROR: 'Something went wrong. Please try again.',
} as const;
