-- Custom types
-- Extend with `alter type public.app_permission add value '...'` / same for app_role
-- as new permissions and roles are needed.
create type public.app_permission as enum ('consultations.read');
create type public.app_role as enum ('admin', 'student');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ROLE PERMISSIONS
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';

alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

-- Every new auth user starts as a student; admins are promoted via seed/manually or from invitation based approach.
create function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_roles (user_id, role)
  values (new.id, 'student')
  on conflict (user_id, role) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row
execute procedure public.handle_new_user();
